version: '2.3'
services:
  stubby4j:
    image: tafael/stubby4j
    ports:
      - "8883:8883"
    environment:
      STUBBY_PORT: 8883
    volumes:
      - ./stubby.yml:/usr/local/stubby.yml

  # Docker compose for netflix conductor + elasticsearch + dynomite
  conductor-server:
    image: tafael/conductor:server
    environment:
      - CONFIG_PROP=/app/config/conductor-config.properties
    ports:
      - 8080:8080
    volumes:
      - ./conductor-config.properties:/app/config/conductor-config.properties
    depends_on:
      elasticsearch:
        condition: service_healthy
      dynomite:
        condition: service_healthy

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: tafael/conductor:ui
    ports:
      - 5000:5000
    links:
      - conductor-server

  dynomite:
    image: v1r3n/dynomite
    ports:
      - 8102:8102
    logging:
      driver: none
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8102'
      interval: 5s
      timeout: 5s
      retries: 12

  elasticsearch:
    ports:
      - 9200:9200
      - 9300:9300
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - transport.host=0.0.0.0
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 12
