# Docker compose for netflix conductor + elasticsearch + dynomite
version: '2'
services:
  stubby4j:
    image: sandokandias/stubby4j-docker
    ports:
    - "8883:8883"
    environment:
      STUBBY_PORT: 8883
    volumes:
    - ./stubby.yml:/usr/local/stubby.yml
